---
title: "Pipe Operator & Comparison"
output: html_document
---
***Pipe Operator***

```{r}
# cancel 2C, 1A
chr <- c('C','C','A','A','B','B','B','B','C')
as.factor(chr) # table on character vector
table(as.factor(chr)) # class conversion
factor(
  chr, levels=c("B", "C", "A")
)
```

```{r}
{
  # do table count on chr
  table(chr) -> tb_chr
  tb_chr
  # ask computer to figure out the level sequence
  sort(tb_chr, decreasing=T) -> sorted_tb_chr
  sorted_tb_chr
  # ask computer to give us names after sorting
  names(sorted_tb_chr)
}
```

```{r}
newLevels <- 
{
  # table check
  table(chr) -> tb_chr
  # sort in decreasing order
  sort(tb_chr, decreasing = T) -> sorted_tb_chr
  # take out table item names
  names(sorted_tb_chr)
}
fct_chr <- factor(chr, levels=newLevels)
table(fct_chr)
```

```{r}
x |> f() |> g(y) |> h(z)
# use x to do f, then take the result
# to do g, then take the result
# to do h
```

```{r}
newLevels <- 
{
  # table check
  chr |> table() |>
  # sort in decreasing order
  sort(decreasing = T) |>
  # take out table item names
  names()
}
fct_chr <- factor(chr, levels=newLevels)
table(fct_chr)
```

```{r}
library(magrittr) # import all the functions in this package
```

```{r}
lubridate::ymd(....)
```

```{r}
df <-
data.frame(
  types = c('C','C','C','A','C','A','A','B','B','B','B','C'),
  response = c(83,59,54,68,64,88,72,73,66,94,53,55)
)

df$types |> class()

df$types %<>% factor()

df$types |> class()

```

```{r}
df$type |> # read: use df$type, to do factor
  factor() |> # to do table
  table()
```

```{r}
# df$type |> print()
df$types %T>%
  print() |> # read: use df$type, to do factor
  factor() # to do table
  table()
```

***Comparison***

```{r}
c(2, 3, -1) > c(3, 3, 5)
c(2, 3, -1) >= c(3, 3, 5)
```

```{r}
pick <- c(2, 3, -1) >= c(3, 3, 5)
c(2, 3, -1)[pick]
```

```{r}
income <- factor(
  c('20,001-30,000','20,001-30,000','less than 10,000','10,001-20,000','10,001-20,000','20,001-30,000','20,001-30,000','20,001-30,000'),
  levels=c("less than 10,000", "10,001-20,000", "20,001-30,000"),
  ordered = T)

income < "10,001-20,000"
income <= "10,001-20,000" 

pick <- income < "10,001-20,000"
income[pick]
which(pick)
income[which(pick)]
```

```{r}
birthdays <- 
  lubridate::ymd(
    c('2017-11-29','2001-11-07','2011-03-30','2014-03-26','2011-04-20','2014-06-11')
  )
birthdays |> class()
# born after 2002
pick <- birthdays > lubridate::ymd("2002-12-31")

birthdays[pick]
```

```{r}
pick <- c(5, 10, -1) > 0
# how many numbers are > 0
sum(pick) # how many element values satisfy the condition (>0)
```

```{r}
pick <- c(5, NA, -1) > 0
pick
sum(pick, na.rm = T)
```
  NA missing a value but there is a value.

```{r}
pick |> 
  na.omit() |> 
  sum()
```

# equal

```{r}
a = 5
```

```{r}
a == 5
```

```{r}
studentGradesInputFromTA <- 
  c(88, 52, 73)
studentGradesFromTeacherCalculation <- 
  c(88, 51, 72)
```

```{r}
pick <- studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation
pick_wrong <- !pick
pick
which(pick_wrong)
```

```{r}
whichIsTheSame <- 
  which(
    pick
  )
which(pick)
print(whichIsTheSame)
```

```{r}
!A == B # negate A then compare it with B
!(A == B) # compare A with B , then negate the result
```

```{r}
print(studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation)
print(!(
  studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation)
  )

whichIsDifferent <- 
  which(
    !(studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation)
  )

print(whichIsDifferent)
```

```{r}
!(studentGradesInputFromTA == 
  studentGradesFromTeacherCalculation) # the same as
studentGradesInputFromTA != 
  studentGradesFromTeacherCalculation
```

```{r}
# compare two character vectors
c("A", "B", "C") == c("B", "A", "C")
!(c("A", "B", "C") == c("B", "A", "C"))
c("A", "B", "C") != c("B", "A", "C")

# list is not atomic vector
list("John", 182, 35) == list("John", 182, 40)
```

```{r}
studentGradesInputFromTA2 <- c(
  82, NA, 73
)
studentGradesInputFromTA2 ==
  studentGradesFromTeacherCalculation
```

```{r}
studentGradesFromTeacherCalculation2 <-
  c(82, NA, 73)

pick <- studentGradesInputFromTA2 == 
  studentGradesFromTeacherCalculation2

sum(pick, na.rm = T)
```

```{r}
identical(studentGradesInputFromTA2,
  studentGradesFromTeacherCalculation2)
```

```{r}
studentGradesInputFromTA2
is.numeric(studentGradesInputFromTA2)
is.na(studentGradesInputFromTA2)
```

```{r}
anyNA(studentGradesInputFromTA2)
```

```{r}
birthdays > lubridate::ymd("2002-12-31")
```

```{r}
birthdays > c(lubridate::ymd("2002-12-31"),
  lubridate::ymd("2002-12-31"), 
  lubridate::ymd("2002-12-31"), 
  lubridate::ymd("2002-12-31"), 
  lubridate::ymd("2002-12-31"), 
  lubridate::ymd("2002-12-31"))

birthdays > rep(lubridate::ymd("2002-12-31"), 6)
```

```{r}
# long vector
long_vctr = c("A", "B", "C", "D")

# short vector
short_vctr = c(1, 2)
# recycle short_vctr
short_vctr_recycles = 
  c(c(1, 2), c(1, 2)) #[1:4]
short_vctr_recycles

# short vector
short_vctr2 = c(1, 2, 3) # length 3
# recycle short_vctr
short_vctr_recycles2 = 
  c(c(1, 2, 3), c(1, 2, 3))[1:4]
short_vctr_recycles2
```

```{r}
vc1 = c("Apr.", "May.")
vc2 = c("1", "1")
paste(vc1, vc2)
paste(c("Apr.", "May."), c("1", "1"))
# use recycling
paste(c("Apr.", "May."), "1")
```

```{r}
rep(1998:2021, 2)
.years <- as.character(rep(1998:2021, each=2))
length(.year)

.halfYearDays <- c("01-01", "07-01")

paste(.years, .halfYearDays, sep="-")
```

## One of them

LHS `%in%`

```{r}
LHS %in% RHS
```

```{r}
# 10 students' majors
majors <- c('economics','law','economics','sociology','sociology','sociology','sociology','economics','statistics','law')
# ? who are from the school of social science ?

# define a set of values that the school contain
set_schoolSocialScience = c("economics", "sociology", "social work")

pickSchoolSocialScience <-
  majors %in% set_schoolSocialScience
print(pickSchoolSocialScience
      )
which(pickSchoolSocialScience)
```

```{r}
"1995" != "1995 " # even space makes a difference
"economics" != "Economics" # case matters
"台灣" != "臺灣"
```
